# Generated by Django 4.0.5 on 2022-06-17 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the kind of this car', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('founded', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Please describe the vehicle for the borrower', max_length=1000)),
                ('kind', models.ManyToManyField(help_text='Select a kind for this car', to='carrental.kind')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrental.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInstance',
            fields=[
                ('plate_no', models.UUIDField(default=uuid.uuid4, help_text='unique ID for this particular vehicle', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Car availability', max_length=1)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='carrental.vehicle')),
            ],
            options={
                'ordering': ['due_back', 'vehicle'],
            },
        ),
    ]
